const mongoose = require('mongoose');

const laptopSchema = new mongoose.Schema({
  image: String,
  title: String,
  prdNameHref: String,
  description: String,
  brand: String,
  price: String,
  ram: String,
  hardDriveSize: String,
  color: String,
  prdDescr2: String,
  prdDescr3: String,
  prdDescr4: String,
  prdDescr5: String,
  prdDescr6: String,
  prdDescr7: String,
  prdDescr8: String,
  prdDescr9: String,
  prdDescr10: String,
  prc: String,
  prdListImgSrc2: String,
  prdName2: String,
  prdNameHref2: String,
  prc2: String,
  prdListImgSrc3: String,
  prdName3: String,
  prdNameHref3: String,
  prc3: String,
  prdListImgSrc4: String,
  prdName4: String,
  prdNameHref4: String,
  prc4: String,
  clr3Href: String,
  clr3: String,
  elps: String,
  tac: String,
  cl: String,
  pnsH: String,
  mo: String,
  prdCtaBtn: String,
  sEtxt1: String,
  prdCtaHref: String,
  ecomBtn: String,
  prdDescr11: String,
  prdDescr12: String,
  noPdp: String,
  noPdp2: String,
  noPdp3: String,
  fs15: String,
  fs152: String,
  field45: String,
  id: String,
});

const Laptop = mongoose.model('Laptop', laptopSchema);

module.exports = Laptop;
